### ISSUE TITLE
OSC receive ?

### ISSUE THREAD

**Issue by alx-1** [256dpi/esp-osc#1]
Hello and nice work !  I was wondering if you also implemented an OSC receive ?  I'm trying to receive OSC messages in an esp-idf project and only get the first term of my bundled message.  Here is the project https://github.com/alx-1/technologies-de-la-fete.

**Comment by 256dpi** [comment]
Thanks! No, I haven't had the time yet to add the receiving part. I'm happy to receive PRs tough!

**Comment by alx-1** [comment]
I can try it, if I am not wrong, you already made the tinyosc functions available ?  Like 'tosc_parseMessage'.  So I would 'only' have to create a receive example? Like a new 'main.c' ?  I'm happy to try it, I have more time than skills though, hence the question before I try it. thxs!

**Comment by 256dpi** [comment]
FYI: Receiving is supported now.
